spring:
   application:
      name: api-gateway-service
   cloud:
      gateway:
        routes:
         - id: user-service
           uri: lb://user-service
           predicates:
             - Path=/users/**
         
         - id: ratnig-serv ice
           uri: lb://ratnig-service
           predicates:
            - Path=/ratings/**
            
         - id: hotel-service
           uri: lb://hotel-service
           predicates:
            - Path=/hotels/**  
server:
   port: 8084
eureka:
   client:
      serviceURL:
         defaultZone: http://localhost:8761/eureka